Repository Card-Forge/forge, pull requests merged in 2024-12, with the labels that each got.

#6653 Fix RollDice
  forge-game/src/main/java/forge/game/GameLog.java
  forge-game/src/main/java/forge/game/GameOutcome.java
  forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
Labels: bug

#6654 Fully unlocked room traits should still be the same (for once per turn)
  forge-game/src/main/java/forge/game/ability/effects/ClassLevelUpEffect.java
  forge-game/src/main/java/forge/game/card/CardFactory.java
Labels: Rules compliance

#6658 Edition updates: PF25, PIO, PMEI
  forge-gui/res/editions/MagicFest 2025.txt
  forge-gui/res/editions/Media Inserts.txt
  forge-gui/res/editions/Pioneer Masters.txt
Labels: Upcoming Set

#6655 Pay cost verbiage
  forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
Labels: Adventure

#6657 fix FCollection
  forge-ai/src/main/java/forge/ai/AiAttackController.java
  forge-ai/src/main/java/forge/ai/ability/PlayAi.java
  forge-core/src/main/java/forge/util/collect/FCollection.java
  forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
  forge-gui-desktop/src/test/java/forge/FCollectionTest.java
Labels: netplay

#6662 Add puzzle PS_FDN2 - Possibility Storm - Foundations 02.
  forge-gui/res/puzzle/PS_FDN2.pzl
Labels: Puzzle Mode

#6663 Edition updates: INR, PIO
  forge-gui/res/editions/Innistrad Remastered.txt
  forge-gui/res/editions/Pioneer Masters.txt
Labels: Upcoming Set

#6664 Fix ConcurrentModificationException
  forge-ai/src/main/java/forge/ai/GameState.java
  forge-game/src/main/java/forge/game/player/Player.java
Labels: Crash fix

#6668 Improve AI for First Responder, improve evaluation for self-sac abilities e.g. Sakura-Tribe Elder.
  forge-ai/src/main/java/forge/ai/CreatureEvaluator.java
  forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
  forge-gui/res/cardsfolder/f/first_responder.txt
Labels: AI

#6665 Fix for noted types for Volo's journal
  forge-ai/src/main/java/forge/ai/ComputerUtil.java
  forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
  forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
  forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
Labels: AI

#6671 Refactor SpellAbilityView canPlay
  forge-ai/src/main/java/forge/ai/AiAttackController.java
  forge-ai/src/main/java/forge/ai/AiController.java
  forge-ai/src/main/java/forge/ai/AiCostDecision.java
  forge-ai/src/main/java/forge/ai/ComputerUtil.java
  forge-ai/src/main/java/forge/ai/ComputerUtilAbility.java
  forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
  forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
  forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
  forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
  forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
  forge-ai/src/main/java/forge/ai/SpellAbilityAi.java
  forge-ai/src/main/java/forge/ai/ability/AttachAi.java
  forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
  forge-ai/src/main/java/forge/ai/ability/CharmAi.java
  forge-ai/src/main/java/forge/ai/ability/ChooseGenericAi.java
  forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
  forge-ai/src/main/java/forge/ai/ability/DelayedTriggerAi.java
  forge-ai/src/main/java/forge/ai/ability/ImmediateTriggerAi.java
  forge-ai/src/main/java/forge/ai/ability/ManaAi.java
  forge-ai/src/main/java/forge/ai/ability/PermanentAi.java
  forge-ai/src/main/java/forge/ai/ability/PermanentNoncreatureAi.java
  forge-ai/src/main/java/forge/ai/ability/RevealAi.java
  forge-ai/src/main/java/forge/ai/ability/VentureAi.java
  forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
  forge-ai/src/main/java/forge/ai/simulation/GameSimulator.java
  forge-ai/src/main/java/forge/ai/simulation/PossibleTargetSelector.java
  forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
  forge-game/src/main/java/forge/game/GameSnapshot.java
  forge-game/src/main/java/forge/game/ability/effects/ChangeTextEffect.java
  forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
  forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
  forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
  forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
  forge-game/src/main/java/forge/game/card/CardFactory.java
  forge-game/src/main/java/forge/game/phase/Untap.java
  forge-game/src/main/java/forge/game/player/PlayerController.java
  forge-game/src/main/java/forge/game/spellability/SpellAbility.java
  forge-game/src/main/java/forge/game/spellability/SpellAbilityView.java
  forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
  forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
  forge-gui/src/main/java/forge/player/HumanCostDecision.java
  forge-gui/src/main/java/forge/player/HumanPlay.java
  forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
  forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Labels: performance

#6673 Edition updates: DCI, INR, PMEI, PRES
  forge-gui/res/editions/DCI Promos.txt
  forge-gui/res/editions/Innistrad Remastered.txt
  forge-gui/res/editions/Media Inserts.txt
  forge-gui/res/editions/Resale Promos.txt
Labels: Upcoming Set

#6674 Fix draft rankings not showing in Adventure Mode on the first pick of a draft
  forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
Labels: bug, Adventure

#6699 Edition updates: DFT, PLG24, PMEI, SLD
  forge-gui/res/editions/Aetherdrift.txt
  forge-gui/res/editions/Love Your LGS 2024.txt
  forge-gui/res/editions/Media and Collaboration Promos.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
Labels: Upcoming Set

#6702 Cherry pick full control fix
  forge-game/src/main/java/forge/game/ability/effects/TokenEffect.java
  forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
  forge-gui/res/cardsfolder/g/giant_inheritance.txt
  forge-gui/res/cardsfolder/l/liege_of_the_hollows.txt
  forge-gui/res/cardsfolder/q/questing_cosplayer.txt
  forge-gui/res/cardsfolder/t/the_rani.txt
Labels: Card Patch

#6707 Fix the AI never playing Chain Lightning
  forge-ai/src/main/java/forge/ai/ability/CopySpellAbilityAi.java
  forge-gui/res/cardsfolder/c/chain_lightning.txt
Labels: AI

#6700 Full Control unleashed
  forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
  forge-core/src/main/java/forge/util/Localizer.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/cost/CostPartWithList.java
  forge-game/src/main/java/forge/game/cost/CostPayment.java
  forge-game/src/main/java/forge/game/player/PlayerController.java
  forge-game/src/main/java/forge/game/spellability/AbilityActivated.java
  forge-game/src/main/java/forge/game/spellability/Spell.java
  forge-gui-desktop/src/main/java/forge/screens/home/settings/CSubmenuPreferences.java
  forge-gui-desktop/src/main/java/forge/screens/home/settings/VSubmenuPreferences.java
  forge-gui-desktop/src/main/java/forge/screens/match/CMatchUI.java
  forge-gui-desktop/src/main/java/forge/screens/match/controllers/CField.java
  forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
  forge-gui-mobile/src/forge/screens/match/MatchController.java
  forge-gui-mobile/src/forge/screens/match/views/VAvatar.java
  forge-gui-mobile/src/forge/screens/settings/SettingsPage.java
  forge-gui/res/languages/de-DE.properties
  forge-gui/res/languages/en-US.properties
  forge-gui/res/languages/es-ES.properties
  forge-gui/res/languages/fr-FR.properties
  forge-gui/res/languages/it-IT.properties
  forge-gui/res/languages/ja-JP.properties
  forge-gui/res/languages/pt-BR.properties
  forge-gui/res/languages/zh-CN.properties
  forge-gui/src/main/java/forge/gamemodes/match/input/InputPassPriority.java
  forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
  forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java
  forge-gui/src/main/java/forge/player/HumanCostDecision.java
  forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Labels: enhancement

#6723 [[Adventure]] Jace quickfix
  forge-gui/res/adventure/common/custom_cards/jace_boss_effect.txt
  forge-gui/res/adventure/common/custom_cards/jaces_signature_hoodie.txt
Labels: Adventure

#6729 Order hand option
  forge-game/src/main/java/forge/game/player/PlayerController.java
  forge-game/src/main/java/forge/game/zone/PlayerZone.java
  forge-game/src/main/java/forge/game/zone/Zone.java
  forge-gui-desktop/src/main/java/forge/screens/home/settings/CSubmenuPreferences.java
  forge-gui-desktop/src/main/java/forge/screens/home/settings/VSubmenuPreferences.java
  forge-gui-mobile/src/forge/screens/settings/SettingsPage.java
  forge-gui/res/languages/de-DE.properties
  forge-gui/res/languages/en-US.properties
  forge-gui/res/languages/es-ES.properties
  forge-gui/res/languages/fr-FR.properties
  forge-gui/res/languages/it-IT.properties
  forge-gui/res/languages/ja-JP.properties
  forge-gui/res/languages/pt-BR.properties
  forge-gui/res/languages/zh-CN.properties
  forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java
  forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Labels: GUI
