Repository Card-Forge/forge, pull requests merged in 2025-04, with the labels that each got.

#7332 Fix creating token with Endure 0
  forge-game/src/main/java/forge/game/ability/effects/EndureEffect.java
Labels: Rules compliance

#7348 Put ForColor for Call of the Spirit Dragons
  forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
  forge-gui/res/cardsfolder/c/call_the_spirit_dragons.txt
Labels: Game Mechanics, AI

#7347 Adventure and Omen as ReplacementEffect in CardState
  forge-game/src/main/java/forge/game/card/CardFactory.java
  forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
  forge-game/src/main/java/forge/game/card/CardState.java
Labels: Game Mechanics

#7355 TDM: Humbling Elder
  forge-gui/res/cardsfolder/h/humbling_elder.txt
Labels: Upcoming Set

#7367 Fix JUPnP initialization
  forge-gui/pom.xml
  forge-gui/src/main/java/forge/gamemodes/net/server/FServerManager.java
Labels: Crash fix

#7371 Add 4 Possibility Storm puzzles
  forge-gui/res/puzzle/PS_DFT2.pzl
  forge-gui/res/puzzle/PS_DFT3.pzl
  forge-gui/res/puzzle/PS_TDM1.pzl
  forge-gui/res/puzzle/PS_TDM2.pzl
Labels: Puzzle Mode

#7369 Unearth: add gain Haste as StaticLayer
  forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
Labels: Game Mechanics

#7385 Svar fallback changes
  forge-game/src/main/java/forge/game/CardTraitBase.java
  forge-game/src/main/java/forge/game/spellability/AbilitySub.java
  forge-game/src/main/java/forge/game/spellability/SpellAbility.java
Labels: Game Mechanics

#7394 Fix Licids being able to reattach without ending the effect first
  forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
Labels: bug

#7393 CantUntap Third Step
  forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
  forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
  forge-game/src/main/java/forge/game/phase/PhaseHandler.java
  forge-game/src/main/java/forge/game/phase/Untap.java
  forge-gui/res/cardsfolder/a/arbalest_elite.txt
  forge-gui/res/cardsfolder/b/bontus_last_reckoning.txt
  forge-gui/res/cardsfolder/c/cinder_marsh.txt
  forge-gui/res/cardsfolder/c/cloudcrest_lake.txt
  forge-gui/res/cardsfolder/d/deep_spawn.txt
  forge-gui/res/cardsfolder/h/hazorets_undying_fury.txt
  forge-gui/res/cardsfolder/h/homarid_warrior.txt
  forge-gui/res/cardsfolder/k/kefnets_last_word.txt
  forge-gui/res/cardsfolder/l/lantern_lit_graveyard.txt
  forge-gui/res/cardsfolder/m/mogg_hollows.txt
  forge-gui/res/cardsfolder/o/oketras_last_mercy.txt
  forge-gui/res/cardsfolder/o/orcish_farmer.txt
  forge-gui/res/cardsfolder/p/pinecrest_ridge.txt
  forge-gui/res/cardsfolder/r/reveka_wizard_savant.txt
  forge-gui/res/cardsfolder/r/rhonass_last_stand.txt
  forge-gui/res/cardsfolder/r/rootwater_depths.txt
  forge-gui/res/cardsfolder/s/samite_alchemist.txt
  forge-gui/res/cardsfolder/s/spectral_bears.txt
  forge-gui/res/cardsfolder/s/spectral_force.txt
  forge-gui/res/cardsfolder/t/thalakos_lowlands.txt
  forge-gui/res/cardsfolder/t/tranquil_garden.txt
  forge-gui/res/cardsfolder/v/vec_townships.txt
  forge-gui/res/cardsfolder/w/waterveil_cavern.txt
Labels: Rules compliance

#7398 Update TokenAi, remove getFirstAttachSpell
  forge-ai/src/main/java/forge/ai/ability/TokenAi.java
Labels: Game Mechanics, AI

#7397 Fix World rule
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/ability/effects/CloneEffect.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/card/CardZoneTable.java
Labels: Rules compliance

#7402 Fix some triggered abilities not finding SVars from effect
  forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
Labels: bug

#7408 Fix always targeting Graveyard with Aura
  forge-gui/src/main/java/forge/player/TargetSelection.java
Labels: GUI

#7420 Make PaperCardFlags serializable
  forge-core/src/main/java/forge/item/PaperCard.java
Labels: Crash fix, netplay

#7415 Fix missing LTB trigger
  forge-game/src/main/java/forge/game/zone/MagicStack.java
Labels: Game Mechanics

#7422 Edition updates: PF25, SLD
  forge-gui/res/editions/MagicFest 2025.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
Labels: Upcoming Set

#7424 Disable TokenCard flag on drafted cards by default.
  forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
Labels: Rules compliance

#7430 Fix UntilHostLeavesPlay corner case
  forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
  forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
  forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
Labels: Rules compliance

#7431 Fix cards in decks reverting to first art in set after game is restarted
  forge-core/src/main/java/forge/card/CardDb.java
  forge-core/src/main/java/forge/card/ICardDatabase.java
  forge-core/src/main/java/forge/deck/CardPool.java
Labels: bug

#7442 Commander Banned and Restricted Announcement for April 22, 2025
  forge-gui/res/formats/Casual/Commander.txt
Labels: Format Changes

#7439 CardEdition: add TokenInSet
  forge-core/src/main/java/forge/StaticData.java
  forge-core/src/main/java/forge/card/CardEdition.java
  forge-core/src/main/java/forge/item/PaperCard.java
  forge-core/src/main/java/forge/item/PaperToken.java
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Game Mechanics, GUI

#7461 Update LDA data for Tarkir: Dragonstorm, add puzzle PS_TDM3 (Tarkir: Dragonstorm 03)
  forge-gui/res/deckgendecks/Modern.lda.dat
  forge-gui/res/deckgendecks/Modern.raw.dat
  forge-gui/res/deckgendecks/Standard.lda.dat
  forge-gui/res/deckgendecks/Standard.raw.dat
  forge-gui/res/puzzle/PS_TDM3.pzl
Labels: enhancement, Puzzle Mode

#7465 Reputation gain fix for Slobad, Kiora and Slime boss quest.
  forge-gui/res/adventure/Shandalar/world/quests.json
Labels: Adventure

#7459 Card: add FacedownImageKey for better logic and set codes
  forge-ai/src/main/java/forge/ai/GameState.java
  forge-ai/src/main/java/forge/ai/ability/CloakAi.java
  forge-ai/src/main/java/forge/ai/ability/ManifestAi.java
  forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
  forge-game/src/main/java/forge/game/GameSnapshot.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/card/CardView.java
  forge-game/src/main/java/forge/trackable/TrackableProperty.java
  forge-gui/src/main/java/forge/player/HumanPlay.java
Labels: Game Mechanics, GUI

#7467 Edition updates: FIC, SLD, UNK, YTDM
  forge-gui/res/editions/Alchemy Tarkir.txt
  forge-gui/res/editions/Final Fantasy Commander.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Unknown Event.txt
Labels: Upcoming Set
