Repository Card-Forge/forge, pull requests merged in 2025-03, with the labels that each got.

#7106 Edition updates: PLG25, PSLDSC, SLD, SPE, YDFT
  forge-gui/res/editions/Alchemy Aetherdrift.txt
  forge-gui/res/editions/Love Your LGS 2025.txt
  forge-gui/res/editions/Marvel's Spider-Man Eternal.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Secret Lair Showcase Planes.txt
Labels: Upcoming Set

#7108 StaticAbility InfectDamage for Phyrexian Unlife
  forge-game/src/main/java/forge/game/player/Player.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityInfectDamage.java
  forge-gui/res/cardsfolder/p/phyrexian_unlife.txt
Labels: Game Mechanics

#7121 Edition updates: TDM
  forge-gui/res/cardsfolder/upcoming/rally_the_monastery.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7129 Jace boss updates
  forge-gui/res/adventure/common/custom_card_pics/Jace Boss Effect.fullborder.jpg
  forge-gui/res/adventure/common/custom_cards/jace_boss_effect.txt
  forge-gui/res/adventure/common/decks/miniboss/jace.dck
Labels: Adventure

#7144 Edition updates: CC2, FIC, PMEI, SLD, TDM
  forge-gui/res/editions/Commander Collection Black.txt
  forge-gui/res/editions/Final Fantasy Commander.txt
  forge-gui/res/editions/Media and Collaboration Promos.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7143 Use StaticAbility for Topsy Turvy
  forge-game/src/main/java/forge/game/Game.java
  forge-game/src/main/java/forge/game/ability/effects/AddPhaseEffect.java
  forge-game/src/main/java/forge/game/ability/effects/FlipCoinEffect.java
  forge-game/src/main/java/forge/game/phase/PhaseHandler.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityTurnPhaseReversed.java
  forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
  forge-gui/res/cardsfolder/t/topsy_turvy.txt
Labels: Game Mechanics

#7141 Added 7 Card booster packs shops in Adventure Mode
  forge-core/src/main/java/forge/item/PaperCard.java
  forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
  forge-gui-mobile/src/forge/adventure/data/RewardData.java
  forge-gui-mobile/src/forge/adventure/util/AdventureEventController.java
  forge-gui-mobile/src/forge/adventure/util/CardUtil.java
  forge-gui-mobile/src/forge/adventure/util/RewardActor.java
  forge-gui-mobile/src/forge/assets/ImageCache.java
  forge-gui/release-files/CHANGES.txt
  forge-gui/res/adventure/Shandalar/world/shops.json
  forge-gui/res/adventure/common/maps/map/main_story/forest_capital.tmx
  forge-gui/res/adventure/common/maps/map/main_story/island_capital.tmx
  forge-gui/res/adventure/common/maps/map/main_story/mountain_capital.tmx
  forge-gui/res/adventure/common/maps/map/main_story/plains_capital.tmx
  forge-gui/res/adventure/common/maps/map/main_story/swamp_capital.tmx
  forge-gui/res/adventure/common/maps/map/towns/forest_town.tmx
  forge-gui/res/adventure/common/maps/map/towns/forest_town_generic.tmx
  forge-gui/res/adventure/common/maps/map/towns/forest_town_identity.tmx
  forge-gui/res/adventure/common/maps/map/towns/forest_town_tribal.tmx
  forge-gui/res/adventure/common/maps/map/towns/island_town.tmx
  forge-gui/res/adventure/common/maps/map/towns/island_town_generic.tmx
  forge-gui/res/adventure/common/maps/map/towns/island_town_identity.tmx
  forge-gui/res/adventure/common/maps/map/towns/island_town_tribal.tmx
  forge-gui/res/adventure/common/maps/map/towns/mountain_town.tmx
  forge-gui/res/adventure/common/maps/map/towns/mountain_town_generic.tmx
  forge-gui/res/adventure/common/maps/map/towns/mountain_town_identity.tmx
  forge-gui/res/adventure/common/maps/map/towns/mountain_town_tribal.tmx
  forge-gui/res/adventure/common/maps/map/towns/plains_town.tmx
  forge-gui/res/adventure/common/maps/map/towns/plains_town_generic.tmx
  forge-gui/res/adventure/common/maps/map/towns/plains_town_identity.tmx
  forge-gui/res/adventure/common/maps/map/towns/plains_town_tribal.tmx
  forge-gui/res/adventure/common/maps/map/towns/swamp_town.tmx
  forge-gui/res/adventure/common/maps/map/towns/swamp_town_generic.tmx
  forge-gui/res/adventure/common/maps/map/towns/swamp_town_identity.tmx
  forge-gui/res/adventure/common/maps/map/towns/swamp_town_tribal.tmx
  forge-gui/res/adventure/common/maps/map/towns/waste_town.tmx
  forge-gui/res/adventure/common/maps/map/towns/waste_town_generic.tmx
  forge-gui/res/adventure/common/maps/map/towns/waste_town_identity.tmx
  forge-gui/res/adventure/common/maps/map/towns/waste_town_tribal.tmx
  forge-gui/res/adventure/common/maps/tileset/buildings.atlas
  forge-gui/res/adventure/common/maps/tileset/buildings.png
  forge-gui/res/adventure/common/maps/tileset/buildings1.png
  forge-gui/res/adventure/common/maps/tileset/buildings2.png
  forge-gui/src/main/java/forge/util/ImageFetcher.java
Labels: Adventure

#7163 Fix North Star
  forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
  forge-game/src/main/java/forge/game/ability/effects/ControlPlayerEffect.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityManaConvert.java
  forge-gui/res/cardsfolder/n/north_star.txt
  forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
Labels: Game Mechanics

#7169 Cleanup "Cleanup" calls
  forge-gui/res/cardsfolder/d/deflecting_palm.txt
  forge-gui/res/cardsfolder/e/eye_for_an_eye.txt
  forge-gui/res/cardsfolder/f/flaming_gambit.txt
  forge-gui/res/cardsfolder/g/grenzos_rebuttal.txt
  forge-gui/res/cardsfolder/h/harms_way.txt
  forge-gui/res/cardsfolder/h/healing_grace.txt
  forge-gui/res/cardsfolder/h/honorable_passage.txt
  forge-gui/res/cardsfolder/i/intervention_pact.txt
  forge-gui/res/cardsfolder/i/invulnerability.txt
  forge-gui/res/cardsfolder/k/kor_chant.txt
  forge-gui/res/cardsfolder/k/kor_dirge.txt
  forge-gui/res/cardsfolder/r/reflect_damage.txt
  forge-gui/res/cardsfolder/r/refraction_trap.txt
  forge-gui/res/cardsfolder/r/reverse_damage.txt
  forge-gui/res/cardsfolder/s/samite_ministration.txt
  forge-gui/res/cardsfolder/s/shadowbane.txt
  forge-gui/res/cardsfolder/s/shining_shoal.txt
  forge-gui/res/cardsfolder/s/spin_into_myth.txt
Labels: Card Cleanup

#7162 Cant untap first step
  forge-game/src/main/java/forge/game/ability/effects/ControlGainEffect.java
  forge-game/src/main/java/forge/game/ability/effects/TapOrUntapAllEffect.java
  forge-game/src/main/java/forge/game/ability/effects/TapOrUntapEffect.java
  forge-game/src/main/java/forge/game/ability/effects/UntapAllEffect.java
  forge-game/src/main/java/forge/game/ability/effects/UntapEffect.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/cost/CostUntap.java
  forge-game/src/main/java/forge/game/cost/CostUntapType.java
  forge-game/src/main/java/forge/game/phase/Untap.java
  forge-game/src/main/java/forge/game/replacement/ReplaceUntap.java
  forge-game/src/main/java/forge/game/replacement/ReplacementEffect.java
  forge-gui/res/cardsfolder/a/altar_golem.txt
  forge-gui/res/cardsfolder/b/basalt_monolith.txt
  forge-gui/res/cardsfolder/b/battered_golem.txt
  forge-gui/res/cardsfolder/b/bewitching_leechcraft.txt
  forge-gui/res/cardsfolder/b/black_carriage.txt
  forge-gui/res/cardsfolder/b/brass_gnat.txt
  forge-gui/res/cardsfolder/b/brass_man.txt
  forge-gui/res/cardsfolder/c/chained_brute.txt
  forge-gui/res/cardsfolder/c/colossus_of_sardia.txt
  forge-gui/res/cardsfolder/d/deep_slumber_titan.txt
  forge-gui/res/cardsfolder/d/depth_charge_colossus.txt
  forge-gui/res/cardsfolder/d/dormant_gomazoa.txt
  forge-gui/res/cardsfolder/d/dwarven_patrol.txt
  forge-gui/res/cardsfolder/e/edge_of_malacol.txt
  forge-gui/res/cardsfolder/e/elaborate_firecannon.txt
  forge-gui/res/cardsfolder/f/famished_paladin.txt
  forge-gui/res/cardsfolder/f/farmstead_gleaner.txt
  forge-gui/res/cardsfolder/f/forsaken_city.txt
  forge-gui/res/cardsfolder/f/freyalises_winds.txt
  forge-gui/res/cardsfolder/g/galvanic_juggernaut.txt
  forge-gui/res/cardsfolder/g/goblin_dirigible.txt
  forge-gui/res/cardsfolder/g/goblin_sharpshooter.txt
  forge-gui/res/cardsfolder/g/goblin_war_wagon.txt
  forge-gui/res/cardsfolder/g/grim_monolith.txt
  forge-gui/res/cardsfolder/g/grimgrin_corpse_born.txt
  forge-gui/res/cardsfolder/i/island_fish_jasconius.txt
  forge-gui/res/cardsfolder/j/jasconian_isle.txt
  forge-gui/res/cardsfolder/j/jokulmorder.txt
  forge-gui/res/cardsfolder/l/leviathan.txt
  forge-gui/res/cardsfolder/l/lurking_roper.txt
  forge-gui/res/cardsfolder/m/mage_ring_responder.txt
  forge-gui/res/cardsfolder/m/mana_vault.txt
  forge-gui/res/cardsfolder/m/marjhan.txt
  forge-gui/res/cardsfolder/m/merieke_ri_berit.txt
  forge-gui/res/cardsfolder/n/nettle_sentinel.txt
  forge-gui/res/cardsfolder/p/phyrexian_colossus.txt
  forge-gui/res/cardsfolder/p/phyrexian_ironfoot.txt
  forge-gui/res/cardsfolder/s/slumbering_cerberus.txt
  forge-gui/res/cardsfolder/s/soldevi_golem.txt
  forge-gui/res/cardsfolder/s/sunstrike_legionnaire.txt
  forge-gui/res/cardsfolder/t/time_vault.txt
  forge-gui/res/cardsfolder/t/traxos_scourge_of_kroog.txt
  forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Labels: Game Mechanics

#7171 Refactor Blinding Beam
  forge-ai/src/main/java/forge/ai/AiController.java
  forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
  forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
  forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
  forge-ai/src/main/java/forge/ai/CreatureEvaluator.java
  forge-ai/src/main/java/forge/ai/ability/ChooseGenericAi.java
  forge-ai/src/main/java/forge/ai/ability/PermanentCreatureAi.java
  forge-ai/src/main/java/forge/ai/ability/PumpAiBase.java
  forge-ai/src/main/java/forge/ai/ability/UntapAi.java
  forge-game/src/main/java/forge/game/GameEntity.java
  forge-game/src/main/java/forge/game/ability/AbilityKey.java
  forge-game/src/main/java/forge/game/ability/effects/SkipPhaseEffect.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/phase/PhaseHandler.java
  forge-game/src/main/java/forge/game/phase/Untap.java
  forge-game/src/main/java/forge/game/replacement/ReplaceBeginPhase.java
  forge-game/src/main/java/forge/game/replacement/ReplacementEffect.java
  forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
  forge-game/src/main/java/forge/game/spellability/SpellAbility.java
  forge-gui/res/cardsfolder/b/blinding_angel.txt
  forge-gui/res/cardsfolder/b/blinding_beam.txt
  forge-gui/res/cardsfolder/c/colfenors_plans.txt
  forge-gui/res/cardsfolder/d/damia_sage_of_stone.txt
  forge-gui/res/cardsfolder/d/dragon_appeasement.txt
  forge-gui/res/cardsfolder/e/empty_city_ruse.txt
  forge-gui/res/cardsfolder/e/eon_hub.txt
  forge-gui/res/cardsfolder/f/false_peace.txt
  forge-gui/res/cardsfolder/f/fasting.txt
  forge-gui/res/cardsfolder/f/fatespinner.txt
  forge-gui/res/cardsfolder/g/gibbering_descent.txt
  forge-gui/res/cardsfolder/i/infernal_sovereign.txt
  forge-gui/res/cardsfolder/i/intruder_alarm.txt
  forge-gui/res/cardsfolder/m/moment_of_silence.txt
  forge-gui/res/cardsfolder/n/necrodominance.txt
  forge-gui/res/cardsfolder/n/necropotence.txt
  forge-gui/res/cardsfolder/n/necropotence_avatar.txt
  forge-gui/res/cardsfolder/n/null_profusion.txt
  forge-gui/res/cardsfolder/p/psychic_possession.txt
  forge-gui/res/cardsfolder/r/recycle.txt
  forge-gui/res/cardsfolder/r/revenant_patriarch.txt
  forge-gui/res/cardsfolder/s/sands_of_time.txt
  forge-gui/res/cardsfolder/s/solitary_confinement.txt
  forge-gui/res/cardsfolder/s/stasis.txt
  forge-gui/res/cardsfolder/s/stonehorn_dignitary.txt
  forge-gui/res/cardsfolder/s/symbiotic_deployment.txt
  forge-gui/res/cardsfolder/t/taigam_sidisis_hand.txt
  forge-gui/res/cardsfolder/t/the_eon_fog.txt
  forge-gui/res/cardsfolder/w/wild_wasteland.txt
  forge-gui/res/cardsfolder/y/yawgmoths_bargain.txt
Labels: Game Mechanics, AI

#7174 Refactor Telekinesis
  forge-ai/src/main/java/forge/ai/AiController.java
  forge-game/src/main/java/forge/game/GameEntity.java
  forge-game/src/main/java/forge/game/ability/AbilityKey.java
  forge-game/src/main/java/forge/game/ability/AbilityUtils.java
  forge-game/src/main/java/forge/game/ability/effects/CountersPutOrRemoveEffect.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/phase/PhaseHandler.java
  forge-game/src/main/java/forge/game/phase/Untap.java
  forge-game/src/main/java/forge/game/replacement/ReplacementEffect.java
  forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
  forge-gui/res/cardsfolder/f/fatespinner.txt
  forge-gui/res/cardsfolder/t/telekinesis.txt
  forge-gui/res/cardsfolder/t/the_horus_heresy.txt
Labels: Game Mechanics, AI

#7182 Edition updates: FIN, SLD, TDM
  forge-gui/res/editions/Final Fantasy.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7201 Edition updates: SPG, TDC, TDM
  forge-gui/res/editions/Special Guests.txt
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7178 Update parseAbilityCost
  forge-game/src/main/java/forge/game/ability/AbilityFactory.java
Labels: Game Mechanics

#7200 Fix Valiant tracking incorrectly with controller change
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java
  forge-game/src/main/java/forge/game/trigger/TriggerBecomesTarget.java
  forge-game/src/main/java/forge/game/zone/MagicStack.java
  forge-gui/res/cardsfolder/g/goblin_artisans.txt
  forge-gui/res/cardsfolder/i/identity_crisis.txt
  forge-gui/res/cardsfolder/u/unbound_flourishing.txt
Labels: bug, Card Cleanup

#7217 Edition updates: TDC, TDM
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7215 Fix AI running into timeout keeping thread running
  forge-ai/src/main/java/forge/ai/AiController.java
Labels: AI, performance

#7219 Fix NPE: Jacob Frye + Escape Detection
  forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
  forge-gui/res/cardsfolder/a/angrath_the_flame_chained.txt
  forge-gui/res/cardsfolder/m/mishra_claimed_by_gix_mishra_lost_to_phyrexia.txt
Labels: Crash fix

#7224 Edition updates: TDC, TDM
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7229 Edition updates: TDC, TDM
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#6780 Update ConniveAi.java
  forge-ai/src/main/java/forge/ai/ability/ConniveAi.java
Labels: keep

#7245 Fix Danny Pink triggering once for each type
  forge-game/src/main/java/forge/game/Game.java
  forge-game/src/main/java/forge/game/GameEntityCounterTable.java
  forge-game/src/main/java/forge/game/trigger/TriggerCounterTypeAddedAll.java
  forge-game/src/main/java/forge/game/trigger/TriggerType.java
  forge-gui/res/cardsfolder/d/danny_pink.txt
  forge-gui/res/cardsfolder/upcoming/stalwart_successor.txt
Labels: Rules compliance

#7247 Edition updates: TDC, TDM, SLD
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7261 Replace first withContext call with more stable AI prediction
  forge-game/src/main/java/forge/game/ability/AbilityKey.java
  forge-game/src/main/java/forge/game/ability/effects/SkipPhaseEffect.java
  forge-game/src/main/java/forge/game/phase/PhaseHandler.java
  forge-game/src/main/java/forge/game/replacement/ReplaceBeginPhase.java
  forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
  forge-gui/res/cardsfolder/c/colfenors_plans.txt
  forge-gui/res/cardsfolder/d/damia_sage_of_stone.txt
  forge-gui/res/cardsfolder/d/desolation_angel.txt
  forge-gui/res/cardsfolder/d/desolation_giant.txt
  forge-gui/res/cardsfolder/d/dragon_appeasement.txt
  forge-gui/res/cardsfolder/e/eon_hub.txt
  forge-gui/res/cardsfolder/f/fasting.txt
  forge-gui/res/cardsfolder/g/gibbering_descent.txt
  forge-gui/res/cardsfolder/i/infernal_sovereign.txt
  forge-gui/res/cardsfolder/m/monstrous_war_leech.txt
  forge-gui/res/cardsfolder/n/necrodominance.txt
  forge-gui/res/cardsfolder/n/necropotence.txt
  forge-gui/res/cardsfolder/n/necropotence_avatar.txt
  forge-gui/res/cardsfolder/n/null_profusion.txt
  forge-gui/res/cardsfolder/p/psychic_possession.txt
  forge-gui/res/cardsfolder/r/recycle.txt
  forge-gui/res/cardsfolder/s/sands_of_time.txt
  forge-gui/res/cardsfolder/s/solitary_confinement.txt
  forge-gui/res/cardsfolder/s/stasis.txt
  forge-gui/res/cardsfolder/s/symbiotic_deployment.txt
  forge-gui/res/cardsfolder/t/taigam_sidisis_hand.txt
  forge-gui/res/cardsfolder/t/the_eon_fog.txt
  forge-gui/res/cardsfolder/w/wild_wasteland.txt
  forge-gui/res/cardsfolder/y/yawgmoths_bargain.txt
Labels: bug

#7267 Edition updates: TDC, TDM
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7276 Some fixes
  forge-game/src/main/java/forge/game/ability/AbilityKey.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/replacement/ReplaceUntap.java
  forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
  forge-game/src/main/java/forge/game/zone/MagicStack.java
  forge-gui/res/cardsfolder/a/artifact_possession.txt
  forge-gui/res/cardsfolder/h/haunting_wind.txt
  forge-gui/res/cardsfolder/i/imprison.txt
  forge-gui/res/cardsfolder/m/mind_bomb.txt
  forge-gui/res/cardsfolder/p/pharikas_spawn.txt
  forge-gui/res/cardsfolder/p/powerleech.txt
Labels: Card Patch

#7279 Edition updates: SLD, TDM
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7254 Endure effect
  forge-ai/src/main/java/forge/ai/SpellApiToAi.java
  forge-ai/src/main/java/forge/ai/ability/EndureAi.java
  forge-game/src/main/java/forge/game/ability/ApiType.java
  forge-game/src/main/java/forge/game/ability/effects/EndureEffect.java
  forge-gui/res/cardsfolder/upcoming/anafenza_unyielding_lineage.txt
  forge-gui/res/cardsfolder/upcoming/descendant_of_storms.txt
  forge-gui/res/cardsfolder/upcoming/dusyut_earthcarver.txt
  forge-gui/res/cardsfolder/upcoming/fortress_kin_guard.txt
  forge-gui/res/cardsfolder/upcoming/krumar_initiate.txt
  forge-gui/res/cardsfolder/upcoming/sinkhole_surveyor.txt
  forge-gui/res/languages/en-US.properties
Labels: Upcoming Set, Game Mechanics

#7298 Edition updates: TDC, TDM
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7297 Omen: first attempt
  forge-ai/src/main/java/forge/ai/SpellAbilityAi.java
  forge-core/src/main/java/forge/card/CardSplitType.java
  forge-core/src/main/java/forge/card/CardStateName.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/card/CardCopyService.java
  forge-game/src/main/java/forge/game/card/CardFactory.java
  forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
  forge-game/src/main/java/forge/game/card/CardView.java
  forge-game/src/main/java/forge/game/spellability/SpellAbility.java
  forge-game/src/main/java/forge/game/zone/PlayerZone.java
  forge-game/src/main/java/forge/trackable/TrackableProperty.java
  forge-gui-desktop/src/main/java/forge/toolbox/imaging/FCardImageRenderer.java
  forge-gui-mobile/src/forge/card/CardImageRenderer.java
  forge-gui-mobile/src/forge/card/CardZoom.java
  forge-gui-mobile/src/forge/toolbox/FChoiceList.java
  forge-gui/res/cardsfolder/upcoming/riling_dawnbreaker_signaling_roar.txt
  forge-gui/res/languages/en-US.properties
  forge-gui/res/lists/TypeLists.txt
  forge-gui/src/main/java/forge/gamemodes/match/AbstractGuiGame.java
Labels: Upcoming Set, Game Mechanics

#7302 Edition updates: PF24, PMEI, PSPL, PW25, SCH, SLP
  forge-gui/res/editions/MagicFest 2024.txt
  forge-gui/res/editions/Media and Collaboration Promos.txt
  forge-gui/res/editions/Secret Lair Showdown.txt
  forge-gui/res/editions/Spotlight Series.txt
  forge-gui/res/editions/Store Championships.txt
  forge-gui/res/editions/Wizards Play Network 2025.txt
Labels: Upcoming Set

#7310 Mobilize X: enable the keyword to pass the SVars to the static
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/card/token/TokenInfo.java
  forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
  forge-game/src/main/java/forge/game/keyword/KeywordInterface.java
  forge-gui/res/cardsfolder/upcoming/infantry_shield.txt
Labels: Upcoming Set, Game Mechanics
