Repository Card-Forge/forge, pull requests merged in 2025-02, with the labels that each got.

#6929 Allow jumpstart/"nosell" cards to be sold for 0 credits
  forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
  forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
  forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
  forge-gui-mobile/src/forge/adventure/util/AdventureEventController.java
  forge-gui/res/adventure/common/custom_cards/sliver_queen_boss_effect.txt
Labels: Adventure

#6973 Fix trigger targeting itself
  forge-game/src/main/java/forge/game/ability/effects/ChangeTargetsEffect.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-game/src/main/java/forge/game/spellability/SpellAbility.java
  forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
Labels: Crash fix

#6974 Edition updates: DFT, DRC, SLD, SPG
  forge-gui/res/editions/Aetherdrift Commander.txt
  forge-gui/res/editions/Aetherdrift.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Special Guests.txt
  forge-gui/res/formats/Archived/Historic/2025-02-11.txt
  forge-gui/res/formats/Sanctioned/Historic.txt
Labels: Upcoming Set

#6975 Edition updates: Fix token name in DFT
  forge-gui/res/editions/Aetherdrift.txt
Labels: Upcoming Set

#6976 [[Adventure]] Fog Trap enemy fix + typo cleanup
  forge-gui/res/adventure/common/maps/map/cave/cave_fog.tmx
  forge-gui/res/adventure/common/world/biomes/blue.json
  forge-gui/res/adventure/common/world/biomes/colorless.json
  forge-gui/res/adventure/common/world/enemies.json
Labels: Adventure

#6971 Fix Primal Wellspring trigger not working with Chun-Li
  forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
  forge-game/src/main/java/forge/game/spellability/SpellAbility.java
  forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
  forge-gui/res/languages/en-US.properties
Labels: bug

#6979 Edition updates: PL25
  forge-gui/res/editions/Year of the Snake 2025.txt
Labels: Upcoming Set

#6983 Fix Blessing applying too late for triggers
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/ability/AbilityUtils.java
  forge-game/src/main/java/forge/game/player/Player.java
Labels: Game Mechanics, Rules compliance

#6957 refactor Max Speed round 1
  forge-game/src/main/java/forge/game/event/GameEventSpeedUp.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-gui/res/cardsfolder/upcoming/aether_syphon.txt
  forge-gui/res/cardsfolder/upcoming/amonkhet_raceway.txt
  forge-gui/res/cardsfolder/upcoming/avishkar_raceway.txt
  forge-gui/res/cardsfolder/upcoming/burnout_bashtronaut.txt
  forge-gui/res/cardsfolder/upcoming/embalmed_ascendant.txt
  forge-gui/res/cardsfolder/upcoming/endrider_catalyzer.txt
  forge-gui/res/cardsfolder/upcoming/endrider_spikespitter.txt
  forge-gui/res/cardsfolder/upcoming/far_fortune_end_boss.txt
  forge-gui/res/cardsfolder/upcoming/gas_guzzler.txt
  forge-gui/res/cardsfolder/upcoming/gastal_raider.txt
  forge-gui/res/cardsfolder/upcoming/gastal_thrillseeker.txt
  forge-gui/res/cardsfolder/upcoming/glitch_ghost_surveyor.txt
  forge-gui/res/cardsfolder/upcoming/goblin_surveyor.txt
  forge-gui/res/cardsfolder/upcoming/hazoret_godseeker.txt
  forge-gui/res/cardsfolder/upcoming/hour_of_victory.txt
  forge-gui/res/cardsfolder/upcoming/howlsquad_heavy.txt
  forge-gui/res/cardsfolder/upcoming/kickoff_celebrations.txt
  forge-gui/res/cardsfolder/upcoming/leonin_surveyor.txt
  forge-gui/res/cardsfolder/upcoming/lightwheel_enhancements.txt
  forge-gui/res/cardsfolder/upcoming/loxodon_surveyor.txt
  forge-gui/res/cardsfolder/upcoming/mendicant_core_guidelight.txt
  forge-gui/res/cardsfolder/upcoming/muraganda_raceway.txt
  forge-gui/res/cardsfolder/upcoming/mutant_surveyor.txt
  forge-gui/res/cardsfolder/upcoming/nesting_bot.txt
  forge-gui/res/cardsfolder/upcoming/pride_of_the_road.txt
  forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
Labels: Upcoming Set

#6958 finish up Max speed refactor
  forge-game/src/main/java/forge/game/CardTraitBase.java
  forge-game/src/main/java/forge/game/spellability/SpellAbilityCondition.java
  forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
  forge-game/src/main/java/forge/game/spellability/SpellAbilityVariables.java
  forge-gui/res/cardsfolder/upcoming/perilous_snare.txt
  forge-gui/res/cardsfolder/upcoming/racers_scoreboard.txt
  forge-gui/res/cardsfolder/upcoming/risen_necroregent.txt
  forge-gui/res/cardsfolder/upcoming/slick_imitator.txt
  forge-gui/res/cardsfolder/upcoming/starting_column.txt
  forge-gui/res/cardsfolder/upcoming/streaking_oilgorger.txt
  forge-gui/res/cardsfolder/upcoming/swiftwing_assailant.txt
  forge-gui/res/cardsfolder/upcoming/vnwxt_verbose_host.txt
  forge-gui/res/cardsfolder/upcoming/walking_sarcophagus.txt
  forge-gui/res/cardsfolder/upcoming/zahur_glorys_past.txt
Labels: Upcoming Set

#6986 StaticAbilityContinous now have AffectedDefined for card list
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
Labels: enhancement

#6982 Add Speed Tracker to Command Zone
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/card/CardView.java
  forge-game/src/main/java/forge/game/card/CounterEnumType.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-game/src/main/java/forge/game/player/PlayerView.java
  forge-game/src/main/java/forge/trackable/TrackableProperty.java
  forge-gui-desktop/src/main/java/forge/view/arcane/CardPanel.java
  forge-gui-mobile/src/forge/card/CardRenderer.java
  forge-gui/res/languages/en-US.properties
  forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
Labels: enhancement

#7000 Edition updates: SLD
  forge-gui/res/editions/Secret Lair Drop Series.txt
Labels: Upcoming Set

#7009 Misc cleanup
  forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
  forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
  forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java
  forge-game/src/main/java/forge/game/staticability/StaticAbility.java
  forge-gui/res/cardsfolder/a/aether_gust.txt
  forge-gui/res/cardsfolder/a/ashioks_erasure.txt
  forge-gui/res/cardsfolder/a/aven_interrupter.txt
  forge-gui/res/cardsfolder/b/brutal_expulsion.txt
  forge-gui/res/cardsfolder/c/commit_memory.txt
  forge-gui/res/cardsfolder/d/divide_by_zero.txt
  forge-gui/res/cardsfolder/e/endless_detour.txt
  forge-gui/res/cardsfolder/e/erestor_of_the_council.txt
  forge-gui/res/cardsfolder/e/eye_of_the_storm.txt
  forge-gui/res/cardsfolder/f/failure_comply.txt
  forge-gui/res/cardsfolder/g/gales_redirection.txt
  forge-gui/res/cardsfolder/g/guile.txt
  forge-gui/res/cardsfolder/h/hullbreaker_horror.txt
  forge-gui/res/cardsfolder/k/knowledge_pool.txt
  forge-gui/res/cardsfolder/k/krark_the_thumbless.txt
  forge-gui/res/cardsfolder/m/mindbreak_trap.txt
  forge-gui/res/cardsfolder/n/neera_wild_mage.txt
  forge-gui/res/cardsfolder/o/obscura_interceptor.txt
  forge-gui/res/cardsfolder/p/possibility_storm.txt
  forge-gui/res/cardsfolder/p/press_the_enemy.txt
  forge-gui/res/cardsfolder/r/radiant_lotus.txt
  forge-gui/res/cardsfolder/r/reprieve.txt
  forge-gui/res/cardsfolder/r/rory_williams.txt
  forge-gui/res/cardsfolder/rebalanced/a-divide_by_zero.txt
  forge-gui/res/cardsfolder/rebalanced/a-hullbreaker_horror.txt
  forge-gui/res/cardsfolder/s/sink_into_stupor_soporific_springs.txt
  forge-gui/res/cardsfolder/s/sliver_queen_avatar.txt
  forge-gui/res/cardsfolder/s/smirking_spelljacker.txt
  forge-gui/res/cardsfolder/s/spell_queller.txt
  forge-gui/res/cardsfolder/s/spellscorn_coven_take_it_back.txt
  forge-gui/res/cardsfolder/s/subtlety.txt
  forge-gui/res/cardsfolder/s/summary_dismissal.txt
  forge-gui/res/cardsfolder/t/talions_throneguard.txt
  forge-gui/res/cardsfolder/u/unsubstantiate.txt
  forge-gui/res/cardsfolder/v/venser_shaper_savant.txt
  forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
Labels: AI, Card Patch

#7022 Effects don't need Exiled trigger
  forge-game/src/main/java/forge/game/GameAction.java
Labels: performance

#7023 Fix Arvinox sometimes failing
  forge-game/src/main/java/forge/game/card/CardProperty.java
  forge-gui/res/cardsfolder/v/vigorous_farming.txt
Labels: bug

#7027 Add GameEventDoorChanged for log
  forge-game/src/main/java/forge/game/GameLogFormatter.java
  forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/event/GameEventCardForetold.java
  forge-game/src/main/java/forge/game/event/GameEventDoorChanged.java
  forge-game/src/main/java/forge/game/event/IGameEventVisitor.java
Labels: Game Mechanics, GUI

#7026 [ADVENTURE] Sorin dungeon cleanup
  forge-gui/res/adventure/common/config.json
  forge-gui/res/adventure/common/custom_cards/sorins_boss_effect.txt
  forge-gui/res/adventure/common/maps/map/vampirecastle/vampirecastle_4.tmx
Labels: Adventure

#7033 Make AI start their engine in Main1
  forge-ai/src/main/java/forge/ai/ComputerUtil.java
Labels: Game Mechanics, AI

#7034 Edition updates: FIC, FIN, SLD, SLP, SLX, TDM
  forge-gui/res/editions/Final Fantasy Commander.txt
  forge-gui/res/editions/Final Fantasy.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Secret Lair Showdown.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
  forge-gui/res/editions/Universes Within.txt
Labels: Upcoming Set

#7035 Speed again
  forge-game/src/main/java/forge/game/card/Card.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityDevotion.java
  forge-gui/res/cardsfolder/a/aether_syphon.txt
  forge-gui/res/cardsfolder/a/amonkhet_raceway.txt
  forge-gui/res/cardsfolder/b/burnout_bashtronaut.txt
  forge-gui/res/cardsfolder/e/embalmed_ascendant.txt
  forge-gui/res/cardsfolder/e/endrider_catalyzer.txt
  forge-gui/res/cardsfolder/e/endrider_spikespitter.txt
  forge-gui/res/cardsfolder/f/far_fortune_end_boss.txt
  forge-gui/res/cardsfolder/g/gas_guzzler.txt
  forge-gui/res/cardsfolder/g/gastal_raider.txt
  forge-gui/res/cardsfolder/g/gastal_thrillseeker.txt
  forge-gui/res/cardsfolder/g/glitch_ghost_surveyor.txt
  forge-gui/res/cardsfolder/g/goblin_surveyor.txt
  forge-gui/res/cardsfolder/h/hour_of_victory.txt
  forge-gui/res/cardsfolder/h/howlsquad_heavy.txt
  forge-gui/res/cardsfolder/k/kickoff_celebrations.txt
  forge-gui/res/cardsfolder/l/leonin_surveyor.txt
  forge-gui/res/cardsfolder/l/lightwheel_enhancements.txt
  forge-gui/res/cardsfolder/l/loxodon_surveyor.txt
  forge-gui/res/cardsfolder/m/mendicant_core_guidelight.txt
  forge-gui/res/cardsfolder/m/muraganda_raceway.txt
  forge-gui/res/cardsfolder/m/mutant_surveyor.txt
  forge-gui/res/cardsfolder/n/nesting_bot.txt
  forge-gui/res/cardsfolder/p/perilous_snare.txt
  forge-gui/res/cardsfolder/p/pride_of_the_road.txt
  forge-gui/res/cardsfolder/r/racers_scoreboard.txt
  forge-gui/res/cardsfolder/r/risen_necroregent.txt
  forge-gui/res/cardsfolder/s/slick_imitator.txt
  forge-gui/res/cardsfolder/s/starting_column.txt
  forge-gui/res/cardsfolder/s/streaking_oilgorger.txt
  forge-gui/res/cardsfolder/s/swiftwing_assailant.txt
  forge-gui/res/cardsfolder/v/vnwxt_verbose_host.txt
  forge-gui/res/cardsfolder/w/walking_sarcophagus.txt
  forge-gui/res/cardsfolder/z/zahur_glorys_past.txt
Labels: Card Patch

#7038 fix issue #7007 (Double Team)
  forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
  forge-game/src/main/java/forge/game/card/Card.java
Labels: bug, Game Mechanics

#7013 Dependency tab
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/GameView.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityLayer.java
  forge-game/src/main/java/forge/trackable/TrackableProperty.java
  forge-gui-desktop/src/main/java/forge/gui/framework/EDocID.java
  forge-gui-desktop/src/main/java/forge/screens/match/CMatchUI.java
  forge-gui-desktop/src/main/java/forge/screens/match/controllers/CDependencies.java
  forge-gui-desktop/src/main/java/forge/screens/match/views/VDependencies.java
  forge-gui/res/defaults/match.xml
  forge-gui/res/languages/de-DE.properties
  forge-gui/res/languages/en-US.properties
  forge-gui/res/languages/es-ES.properties
  forge-gui/res/languages/fr-FR.properties
  forge-gui/res/languages/it-IT.properties
  forge-gui/res/languages/ja-JP.properties
  forge-gui/res/languages/pt-BR.properties
  forge-gui/res/languages/zh-CN.properties
  forge-gui/src/main/java/forge/gamemodes/match/AbstractGuiGame.java
  forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
  forge-gui/src/main/java/forge/gui/interfaces/IGuiGame.java
Labels: GUI, Desktop

#7046 Edition updates: FCA, FIC, FIN, SLD
  forge-gui/res/editions/Final Fantasy Commander.txt
  forge-gui/res/editions/Final Fantasy Through the Ages.txt
  forge-gui/res/editions/Final Fantasy.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
Labels: Upcoming Set

#7050 Fix corner case with Jace, Wielder of Mysteries
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/GameEndReason.java
  forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
  forge-game/src/main/java/forge/game/ability/effects/AttachEffect.java
  forge-game/src/main/java/forge/game/ability/effects/GameWinEffect.java
  forge-game/src/main/java/forge/game/player/Player.java
Labels: Rules compliance

#7054 Fix Well-Laid Plans
  forge-game/src/main/java/forge/game/replacement/ReplaceDamage.java
Labels: bug

#7060 Edition updates: SLD, TDC, TDM
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
  forge-gui/res/editions/Tarkir Dragonstorm.txt
Labels: Upcoming Set

#7071 Edition updates: TDC
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
Labels: Upcoming Set

#7072 CostBehold: add Special Reveal Cost
  forge-ai/src/main/java/forge/ai/AiCostDecision.java
  forge-game/src/main/java/forge/game/cost/Cost.java
  forge-game/src/main/java/forge/game/cost/CostBehold.java
  forge-game/src/main/java/forge/game/cost/CostReveal.java
  forge-game/src/main/java/forge/game/cost/ICostVisitor.java
  forge-gui/res/cardsfolder/upcoming/sarkhan_dragon_ascendant.txt
  forge-gui/src/main/java/forge/player/HumanCostDecision.java
Labels: Upcoming Set, Game Mechanics

#7075 Fix battles attacking/blocking
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
  forge-game/src/main/java/forge/game/combat/CombatUtil.java
  forge-game/src/main/java/forge/game/cost/CostExile.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-gui/src/main/java/forge/player/HumanCostDecision.java
Labels: Crash fix

#7079 Edition updates
  forge-gui/res/cardsfolder/upcoming/elsha_threefold_master.txt
  forge-gui/res/cardsfolder/upcoming/neriv_crackling_vanguard.txt
  forge-gui/res/editions/Alchemy Aetherdrift.txt
  forge-gui/res/editions/Secret Lair Drop Series.txt
  forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
Labels: Upcoming Set

#7081 Fix All in Good Time
  forge-ai/src/main/java/forge/ai/AiController.java
  forge-game/src/main/java/forge/game/ability/ApiType.java
  forge-game/src/main/java/forge/game/ability/effects/AddTurnEffect.java
  forge-game/src/main/java/forge/game/ability/effects/ChooseCompanionEffect.java
  forge-game/src/main/java/forge/game/ability/effects/SetInMotionEffect.java
  forge-game/src/main/java/forge/game/player/Player.java
  forge-game/src/main/java/forge/game/staticability/StaticAbilityCantSetSchemesInMotion.java
  forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
  forge-game/src/main/java/forge/game/trigger/TriggerSetInMotion.java
  forge-gui/res/cardsfolder/b/barrel_down_sokenzan.txt
  forge-gui/res/cardsfolder/c/charge_across_the_araba.txt
  forge-gui/res/cardsfolder/m/my_laughter_echoes.txt
  forge-gui/res/cardsfolder/p/plow_through_reito.txt
  forge-gui/res/cardsfolder/s/sink_into_takenuma.txt
Labels: Card Cleanup

#7089 Edition updates: YDFT
  forge-gui/res/editions/Alchemy Aetherdrift.txt
Labels: Upcoming Set

#7099 Fix missing SpellDescription
  forge-game/src/main/java/forge/game/GameAction.java
  forge-game/src/main/java/forge/game/ability/effects/ChooseCardEffect.java
  forge-game/src/main/java/forge/game/ability/effects/SetStateEffect.java
  forge-game/src/main/java/forge/game/cost/CostBehold.java
  forge-game/src/main/java/forge/game/cost/CostForage.java
  forge-gui/res/cardsfolder/b/beledros_witherbloom.txt
  forge-gui/res/cardsfolder/c/call_to_the_void.txt
  forge-gui/res/cardsfolder/c/critical_hit.txt
  forge-gui/res/cardsfolder/d/defenders_of_humanity.txt
  forge-gui/res/cardsfolder/d/devour_intellect.txt
  forge-gui/res/cardsfolder/g/global_ruin.txt
  forge-gui/res/cardsfolder/n/negan_the_cold_blooded.txt
  forge-gui/res/cardsfolder/s/sigurd_jarl_of_ravensthorpe.txt
  forge-gui/res/cardsfolder/s/spectral_steel.txt
  forge-gui/res/cardsfolder/s/sundering_titan.txt
Labels: Card Cleanup
